### ISSUE TITLE
Mod "Extended Building Width" not working properly

### ISSUE THREAD

**Issue by realMars00** [pakvg85/ONIMods#1]
## Describe the bug
title

## Steps to Reproduce
1. When all mods are enabled together, game crashes on main menu.
2. Disable other mods, only enable this one, it can enter the main menu; then enable the others, restart, can also enter the main menu, but when I start a new game, the game will exit after loading screen, just before dupes choose screen. And in this case, nothing pops up when I click the mod option button.

## Output Log file 'Player.log' (obligatory)
The game log file Player.log is situated in this directory: %userprofile%\AppData\LocalLow\Klei\Oxygen Not Included
[Player.log](https://github.com/pakvg85/ONIMods/files/12506049/Player.log)

**Comment by pakvg85** [comment]
Is DLC 'Spaced Out!' enabled?

**Comment by realMars00** [comment]
I think I just forgot to remove the mods in the local folder, so many mods are enabled twice. Please check this new log file.
And yes, DLC enabled.
[Player.log](https://github.com/pakvg85/ONIMods/files/12506194/Player.log)

**Comment by pakvg85** [comment]
Ok, thank you! The game crashes because of conflict with 'Decor Pack I - Classy Glass' mod, I'll try to fix it

**Comment by pakvg85** [comment]
Should be fine now

**Comment by realMars00** [comment]
Uh.. seems a different error occurred.
[error.txt](https://github.com/pakvg85/ONIMods/files/12506420/error.txt)
[Player.log](https://github.com/pakvg85/ONIMods/files/12506421/Player.log)

**Comment by pakvg85** [comment]
Guess there will be more conflicts.
Try replacing the mod's .dll file with the one from release page:
https://github.com/pakvg85/ONIMods/releases/tag/v1.0.6

**Comment by pakvg85** [comment]
Also please attach new Player.log after launching the game with the new ExtendedBuildingWidth.dll lib

**Comment by realMars00** [comment]
This one works, now I can enter the game and load saves.
[Player.log](https://github.com/pakvg85/ONIMods/files/12506703/Player.log)
